### ISSUE TITLE
need kernel-headers on centos

### ISSUE THREAD

**Issue by tkelman** [staticfloat/julia-ansible-scripts#2]
cc @staticfloat and @yuyichao Can't find which yml file to do this in, is it even this repo? ref https://build.julialang.org/builders/build_centos7.1-x64/builds/1215/steps/shell_1/logs/stdio

```
/home/centos/buildbot/slave/build_centos7_1-x64/build/src/cgmemmgr.cpp:19:29: fatal error: linux/memfd.h: No such file or directory
 #    include <linux/memfd.h>
                             ^
compilation terminated.
make[1]: *** [cgmemmgr.o] Error 1
```

**Comment by yuyichao** [comment]
FWIW, this is only for the `MFD_CLOEXEC` and we can just define it as `0x0001U` if we have to.
I already guard the include with `#  ifdef __NR_memfd_create` and I thought that should be enough.....

**Comment by tkelman** [comment]
I think I found it https://github.com/staticfloat/ansible-julia_buildslave/blob/master/tasks/packages_yum.yml, but if kernel-devel is installed then I'd think kernel-headers is too. Sure the include shouldn't be `sys/memfd.h` ?

**Comment by yuyichao** [comment]
Maybe this is an ArchLinux packaging bug? I don't have `sys/memfd.h` even though it's indeed what the man page says.

**Comment by tkelman** [comment]
I think the centos 7 kernel may be too old for memfd_create anyway? It looks from http://lxr.free-electrons.com/source/include/uapi/linux/memfd.h that if all you're using it is for that one constant, just hardcode it.
